set-window-option -g mode-keys vi
set-window-option -g clock-mode-style 24

set-option -g mouse on

set-option -g prefix C-b
bind C-b send-prefix

set-option -g base-index 1
set-window-option -g pane-base-index 1

bind-key x kill-pane
bind-key & kill-window

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -sel clip > /dev/null"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -i -sel clip > /dev/null"

bind Escape copy-mode
