set-window-option -g mode-keys vi

set-window-option -g clock-mode-style 24

set-option -g default-shell /usr/bin/nu

set-option -g mouse on

set-option -g prefix C-b
bind C-b send-prefix

set-option -g base-index 1
set-window-option -g pane-base-index 1

bind-key x kill-pane
bind-key & kill-window
